import { builtinModules } from "node:module";
import process from "node:process";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const jsContext = await esbuild.context({
	banner: {
		js: banner,
	},
	alias: {
		"@": fileURLToPath(new URL("./src", import.meta.url)),
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	tsconfig: fileURLToPath(new URL("./tsconfig.json", import.meta.url)),
	outfile: "main.js",
	minify: prod,
});

// Obsidian reads styles.css from the plugin folder, so the bundle keeps that
// name and stays unminified: it is the file a user or theme author inspects.
// The target lowers nesting; color-mix() already sets the floor at Chrome 111.
const cssContext = await esbuild.context({
	banner: {
		css: banner,
	},
	entryPoints: ["src/styles/index.css"],
	bundle: true,
	target: ["chrome111", "safari16.4"],
	logLevel: "info",
	outfile: "styles.css",
});

if (prod) {
	await Promise.all([jsContext.rebuild(), cssContext.rebuild()]);
	process.exit(0);
} else {
	await Promise.all([jsContext.watch(), cssContext.watch()]);
}
